import { supabase } from './supabase-client';

export interface Product {
  id: number;
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  brand: string;
  brandSlug: string;
  substance: string;
  classification: string;
  form: string;
  halfLife: string;
  dosage: string;
  acne: string;
  waterRetention: string;
  hbp: string;
  hepatotoxicity: string;
  aromatization: string;
  image: string;
  intPrice: number;
  usaPrice: number;
  intOriginalPrice?: number;
  usaOriginalPrice?: number;
  discounts: string[];
  suggestions: string[];
  ribbons: string[];
  labTested: boolean;
  labTestImage?: string;
  featured?: boolean;
  bestSeller?: boolean;
  description: string;
}

export const products: Product[] = [
  {
    id: 2807,
    slug: 'dianabol-2807',
    name: 'DIANABOL 20',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Methandrostanolone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 20 MG',
    halfLife: '3.2–4.5 HOURS',
    dosage: 'MEN 20 MG/DAY',
    acne: 'YES',
    waterRetention: 'HIGH',
    hbp: 'YES',
    hepatotoxicity: 'YES',
    aromatization: 'HIGH',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/dianabol-20-2807--s512.webp',
    intPrice: 28.5,
    usaPrice: 58,
    intOriginalPrice: 57,
    usaOriginalPrice: 116,
    discounts: ['You will save $28.50'],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International', '-50% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/dianabol-20-lab-test-2025-04-18.webp',
    featured: true,
    description: 'Dianabol 20 by Dragon Pharma is one of the most popular oral anabolic steroids. Methandrostanolone promotes rapid muscle mass and strength gains.',
  },
  {
    id: 2822,
    slug: 'winstrol-2822',
    name: 'WINSTROL 50',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Stanozolol',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 50 MG',
    halfLife: '9 HOURS',
    dosage: 'MEN 10–20 MG/DAY',
    acne: 'YES',
    waterRetention: 'NO',
    hbp: 'PERHAPS',
    hepatotoxicity: 'YES',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/winstrol-50-2822--s512.webp',
    intPrice: 40,
    usaPrice: 75,
    intOriginalPrice: 80,
    usaOriginalPrice: 150,
    discounts: ['You will save $40.00'],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International', '-50% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/winstrol-50-lab-test-2025-04-18.webp',
    featured: true,
    description: 'Winstrol 50 (Stanozolol) is a popular cutting steroid known for enhancing strength and speed without significant water retention.',
  },
  {
    id: 2917,
    slug: 'cypionat-2917',
    name: 'CYPIONAT 250',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Testosterone Cypionate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 250 MG',
    halfLife: '15–16 DAYS',
    dosage: 'MEN 50–200 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'YES',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/cypionat-2917--s512.webp',
    intPrice: 26.5,
    usaPrice: 101,
    intOriginalPrice: 53,
    discounts: ['You will save $26.50'],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International', '-50% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/cypionat-lab-test-2026-03-20.webp',
    featured: true,
    description: 'Cypionat 250 is a long-acting testosterone ester commonly used in bulking cycles for massive muscle and strength gains.',
  },
  {
    id: 2916,
    slug: 'eq-2916',
    name: 'EQ 300',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Boldenone Undecylenate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 300 MG',
    halfLife: '14 DAYS',
    dosage: 'MEN 400–1000 MG/WEEK',
    acne: 'RARELY',
    waterRetention: 'LOW',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'LOW',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/eq-300-2916--s512.webp',
    intPrice: 66,
    usaPrice: 116,
    discounts: [],
    suggestions: ["Buy 3 and get 1 of 'EQ 300' for FREE", 'Buy 5+ for $62.70 and save $16.50'],
    ribbons: ['Lab Tested', 'Domestic & International', "Buy 3 Get 1 FREE"],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/eq-300-lab-test-2025-11-20.webp',
    featured: true,
    description: 'EQ 300 (Boldenone Undecylenate) promotes lean muscle growth and increased appetite with low estrogenic activity.',
  },
  {
    id: 2918,
    slug: 'masteron-2918',
    name: 'MASTERON 100',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Drostanolone Propionate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 100 MG',
    halfLife: '1–1.5 DAYS',
    dosage: 'MEN 300–700 MG/WEEK',
    acne: 'YES',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/masteron-100-2918--s512.webp',
    intPrice: 113,
    usaPrice: 142,
    discounts: [],
    suggestions: ["Buy 3 and get 1 of 'Masteron 100' for FREE", 'Buy 5+ for $107.35 and save $28.25'],
    ribbons: ['Domestic & International', "Buy 3 Get 1 FREE"],
    labTested: false,
    description: 'Masteron 100 (Drostanolone Propionate) is a popular cutting compound that adds hardness and definition.',
  },
  {
    id: 2919,
    slug: 'masteron-2919',
    name: 'MASTERON 200',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Drostanolone Enanthate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 200 MG',
    halfLife: '8 DAYS',
    dosage: 'MEN 400–600 MG/WEEK',
    acne: 'YES',
    waterRetention: '25.00%',
    hbp: 'YES',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/masteron-200-2919--s512.webp',
    intPrice: 125,
    usaPrice: 150,
    discounts: [],
    suggestions: ["Buy 2 and get 1 of 'Masteron 200' for FREE"],
    ribbons: ['Lab Tested', 'Domestic & International', "Buy 2 Get 1 FREE"],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/masteron-200-lab-test-2026-03-25.webp',
    description: 'Masteron 200 (Drostanolone Enanthate) offers longer-lasting effects with fewer injections than the propionate version.',
  },
  {
    id: 46298,
    slug: 'dragontropin-46298',
    name: 'DRAGONTROPIN HGH 100 IU',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Somatropin (R-HGH)',
    classification: 'GROWTH HORMONE ANALOG',
    form: '1 KIT x 2 ML VIALS x 10 IU (LYOPHILIZED POWDER)',
    halfLife: '2.5–3 DAYS',
    dosage: 'MEN 4–10 IU/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/dragontropin-hgh-100-iu-46298--s512.webp',
    intPrice: 275,
    usaPrice: 400,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/dragontropin-100-lab-test-2026-03-20.webp',
    bestSeller: true,
    description: 'Dragontropin HGH 100 IU is Dragon Pharma\'s premium Human Growth Hormone, lab-verified for purity and potency.',
  },
  {
    id: 86967,
    slug: 'dragontropin-hgh-200-iu-86967',
    name: 'DRAGONTROPIN HGH 200 IU',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Somatropin (R-HGH)',
    classification: 'HUMAN GROWTH HORMONE (HGH)',
    form: '1 KIT x 2 ML VIALS x 20 IU (LYOPHILIZED POWDER)',
    halfLife: '2–4 HOURS',
    dosage: '2–6 IU/DAY',
    acne: 'NO',
    waterRetention: 'POSSIBLE AT HIGH DOSES',
    hbp: 'RARE',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/dragontropin-hgh-200-iu-86967--s512.webp',
    intPrice: 475,
    usaPrice: 650,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/dragontropin-200-lab-test-2026-03-20.webp',
    bestSeller: true,
    description: 'The 200 IU kit of Dragontropin HGH offers exceptional value for long-term growth hormone therapy and anti-aging protocols.',
  },
  {
    id: 48731,
    slug: 'bpc-157-48731',
    name: 'BPC 157',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Pentadecapeptide',
    classification: 'BODY PROTECTING COMPOUND',
    form: '2 ML VIAL x 5 MG (LYOPHILIZED POWDER)',
    halfLife: '~4–6 HOURS',
    dosage: '200–500 MCG/DAY',
    acne: 'NOT REPORTED',
    waterRetention: 'NONE',
    hbp: 'NO KNOWN IMPACT',
    hepatotoxicity: 'NONE',
    aromatization: 'DOES NOT AROMATIZE',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/bpc-157-48731--s512.webp',
    intPrice: 24,
    usaPrice: 48,
    intOriginalPrice: 40,
    usaOriginalPrice: 80,
    discounts: ['You will save $16.00'],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International', '-40% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/bpc-157-lab-test-2024-03-22.webp',
    bestSeller: true,
    description: 'BPC 157 is a body-protecting peptide that promotes healing of tendons, muscles, and joints while improving gut health.',
  },
  {
    id: 74034,
    slug: 'mazdutide-10-mg-74034',
    name: 'MAZDUTIDE 10 MG',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Mazdutide',
    classification: 'DUAL GLUCAGON AGONIST; GLP-1 AGONIST',
    form: '2 ML VIAL x 10 MG (LYOPHILIZED POWDER)',
    halfLife: '158–180 HOURS',
    dosage: 'MEN 3–9 MG/WEEK',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/mazdutide-10-mg-74034--s512.webp',
    intPrice: 60,
    usaPrice: 108,
    intOriginalPrice: 100,
    usaOriginalPrice: 180,
    discounts: ['You will save $40.00'],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International', '-40% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/mazdutide-lab-test-2024-09-13.webp',
    bestSeller: true,
    description: 'Mazdutide is a next-generation dual GLP-1/glucagon receptor agonist for effective weight management and metabolic health.',
  },
  {
    id: 45650,
    slug: 'mots-c-10mg-45650',
    name: 'MOTS-C 10 MG',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'MOTS-C',
    classification: 'MITOCHONDRIAL-DERIVED PEPTIDE',
    form: '2 ML VIAL x 10 MG (LYOPHILIZED POWDER)',
    halfLife: '~3–4 HOURS',
    dosage: '5–10 MG/WEEK (SPLIT INJECTIONS)',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO IMPACT',
    hepatotoxicity: 'NONE',
    aromatization: 'DOES NOT AROMATIZE',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/mots-c-10-mg-45650--s512.webp',
    intPrice: 42,
    usaPrice: 84,
    intOriginalPrice: 70,
    usaOriginalPrice: 140,
    discounts: ['You will save $28.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-40% OFF'],
    labTested: false,
    bestSeller: true,
    description: 'MOTS-C is a mitochondria-derived peptide that regulates metabolism, improves insulin sensitivity, and enhances physical performance.',
  },
  {
    id: 2838,
    slug: 'anavar-2838',
    name: 'ANAVAR 10',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Oxandrolone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 10 MG',
    halfLife: '9 HOURS',
    dosage: 'MEN 2.5–50 MG/DAY',
    acne: 'RARELY',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/anavar-10-2838--s512.webp',
    intPrice: 125,
    usaPrice: 175,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    bestSeller: true,
    description: 'Anavar 10 (Oxandrolone) is a mild yet effective oral steroid popular for cutting cycles, lean muscle retention, and strength.',
  },
  {
    id: 2866,
    slug: 'anavar-2866',
    name: 'ANAVAR 50',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Oxandrolone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 50 MG',
    halfLife: '9 HOURS',
    dosage: 'MEN 2.5–50 MG/DAY',
    acne: 'RARELY',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/anavar-50-2866--s512.webp',
    intPrice: 275,
    usaPrice: 400,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-50-lab-test-2026-01-13.webp',
    bestSeller: true,
    description: 'Anavar 50 offers a higher dose of Oxandrolone for experienced users seeking maximum strength and lean muscle gains.',
  },
  {
    id: 3166,
    slug: 'clenbuterol-3166',
    name: 'CLENBUTEROL',
    category: 'Fat Loss',
    categorySlug: 'fat-loss-397',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Clenbuterol',
    classification: 'BETA-2 AGONIST; BRONCHODILATOR',
    form: '100 TABS x 40 MCG',
    halfLife: '35–40 HOURS',
    dosage: '20–120 MCG/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'YES',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/clenbuterol-3166--s512.webp',
    intPrice: 44,
    usaPrice: 80,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    bestSeller: true,
    description: 'Clenbuterol is a powerful thermogenic agent that increases metabolic rate and accelerates fat burning.',
  },
  {
    id: 2912,
    slug: 'sustanon-2912',
    name: 'SUSTANON 270',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Testosterone Mix',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '10 ML VIAL x 270 MG',
    halfLife: '7–8 DAYS',
    dosage: 'MEN 250–1000 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'YES',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/sustanon-2912--s512.webp',
    intPrice: 61,
    usaPrice: 105,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    bestSeller: true,
    description: 'Sustanon 270 is a blend of four testosterone esters designed for sustained release and steady anabolic activity.',
  },
  {
    id: 36988,
    slug: 'testo-blend-36988',
    name: 'TESTO BLEND 350',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Testosterone Enanthate',
    classification: 'INJECTABLE ANABOLIC ANDROGENIC STEROID',
    form: '10 ML VIAL x 350 MG',
    halfLife: '7–8 DAYS',
    dosage: 'MEN 350 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'YES',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/testo-blend-350-36988--s512.webp',
    intPrice: 66,
    usaPrice: 105,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    bestSeller: true,
    description: 'Testo Blend 350 combines Testosterone Propionate, Cypionate, and Enanthate for optimal synergistic anabolic effects.',
  },
  {
    id: 2924,
    slug: 'trenbolone-2924',
    name: 'TRENBOLONE 200',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Trenbolone Enanthate',
    classification: 'ANDROGEN ESTER; ANABOLIC STEROID; PROGESTOGEN',
    form: '10 ML VIAL x 200 MG',
    halfLife: '5 DAYS',
    dosage: 'MEN 75–100 MG/WEEK',
    acne: 'RARELY',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'YES',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/trenbolone-200-2924--s512.webp',
    intPrice: 134,
    usaPrice: 160,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/tren-200-lab-test-2025-04-18.webp',
    bestSeller: true,
    description: 'Trenbolone 200 is one of the most powerful anabolic steroids available, delivering exceptional muscle hardness and strength.',
  },
  {
    id: 2913,
    slug: 'enantat-2913',
    name: 'ENANTAT 250',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Testosterone Enanthate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 250 MG',
    halfLife: '10–14 DAYS',
    dosage: 'MEN 250–500 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'YES',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/enantat-250-2913--s512.webp',
    intPrice: 44,
    usaPrice: 88,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/enantat-250-lab-test-2026-03-25.webp',
    description: 'Enantat 250 is a classic testosterone enanthate formulation ideal for beginner and experienced bulking cycles.',
  },
  {
    id: 2930,
    slug: 'cut-mix-2930',
    name: 'CUT MIX 150',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Testosterone Propionate / Drostanolone Propionate / Trenbolone Acetate',
    classification: 'ANABOLIC STEROID BLEND',
    form: '10 ML VIAL x 150 MG',
    halfLife: '1–2 DAYS',
    dosage: 'MEN 150–450 MG/WEEK',
    acne: 'YES',
    waterRetention: 'LOW',
    hbp: 'PERHAPS',
    hepatotoxicity: 'LOW',
    aromatization: 'LOW',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/cut-mix-150-2930--s512.webp',
    intPrice: 72,
    usaPrice: 120,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/cut-mix-lab-test-2026-03-25.webp',
    description: 'Cut Mix 150 is a powerful injectable blend for cutting cycles, combining three fast-acting esters for rapid results.',
  },
  {
    id: 5001,
    slug: 'rad140-5001',
    name: 'RAD 140 (TESTOLONE)',
    category: 'SARMs',
    categorySlug: 'sarms-2034',
    brand: 'Stealth Labs USA',
    brandSlug: 'stealth-labs-usa-3071',
    substance: 'Testolone (RAD-140)',
    classification: 'SELECTIVE ANDROGEN RECEPTOR MODULATOR',
    form: '50 TABS x 10 MG',
    halfLife: '20–24 HOURS',
    dosage: 'MEN 10–20 MG/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=800&auto=format&fit=crop',
    intPrice: 45,
    usaPrice: 80,
    intOriginalPrice: 90,
    usaOriginalPrice: 160,
    discounts: ['You will save $45.00'],
    suggestions: ['Buy 3 get 1 FREE'],
    ribbons: ['Domestic & International', '-50% OFF', 'Buy 3 Get 1 FREE'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: true,
    description: 'RAD-140 (Testolone) is a highly effective selective androgen receptor modulator popular for adding dry muscle tissue and boosting physical endurance.',
  },
  {
    id: 5002,
    slug: 'mk677-5002',
    name: 'MK 677 (IBUTAMOREN)',
    category: 'SARMs',
    categorySlug: 'sarms-2034',
    brand: 'Stealth Labs USA',
    brandSlug: 'stealth-labs-usa-3071',
    substance: 'Ibutamoren (MK-677)',
    classification: 'GROWTH HORMONE SECRETAGOGUE',
    form: '50 TABS x 25 MG',
    halfLife: '24 HOURS',
    dosage: 'MEN 12.5–25 MG/DAY',
    acne: 'NO',
    waterRetention: 'LOW',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=800&auto=format&fit=crop',
    intPrice: 50,
    usaPrice: 90,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: true,
    description: 'MK-677 (Ibutamoren) acts as a potent growth hormone secretagogue, increasing IGF-1 levels to promote appetite, sleep quality, and muscle recovery.',
  },
  {
    id: 6001,
    slug: 'sildenafil-6001',
    name: 'VIAGRA (SILDENAFIL 100)',
    category: 'Sexual Health',
    categorySlug: 'sexual-health-415',
    brand: 'Generic Asia',
    brandSlug: 'generic-asia-3391',
    substance: 'Sildenafil Citrate',
    classification: 'PDE5 INHIBITOR',
    form: '30 TABS x 100 MG',
    halfLife: '4 HOURS',
    dosage: '50–100 MG BEFORE ACTIVITY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO (LOWERS BP)',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=800&auto=format&fit=crop',
    intPrice: 20,
    usaPrice: 35,
    intOriginalPrice: 40,
    usaOriginalPrice: 70,
    discounts: ['You will save $20.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-50% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: true,
    description: 'Sildenafil Citrate is the active compound in Viagra, widely used to treat erectile dysfunction and enhance sexual performance and recovery times.',
  },
  {
    id: 6002,
    slug: 'tadalafil-6002',
    name: 'CIALIS (TADALAFIL 20)',
    category: 'Sexual Health',
    categorySlug: 'sexual-health-415',
    brand: 'Generic Asia',
    brandSlug: 'generic-asia-3391',
    substance: 'Tadalafil',
    classification: 'PDE5 INHIBITOR',
    form: '30 TABS x 20 MG',
    halfLife: '17.5 HOURS',
    dosage: '10–20 MG BEFORE ACTIVITY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=800&auto=format&fit=crop',
    intPrice: 22,
    usaPrice: 40,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: false,
    description: 'Tadalafil (Cialis) is a long-lasting PDE5 inhibitor providing support for erectile dysfunction and workout pumps for up to 36 hours.',
  },
  {
    id: 7001,
    slug: 'clomid-7001',
    name: 'CLOMID 50',
    category: 'Post-Cycle Therapy (PCT)',
    categorySlug: 'post-cycle-therapy-3855',
    brand: 'Axiolabs',
    brandSlug: 'axiolabs-2078',
    substance: 'Clomiphene Citrate',
    classification: 'SERM (ESTROGEN RECEPTOR ANTAGONIST)',
    form: '50 PILLS x 50 MG',
    halfLife: '5–7 DAYS',
    dosage: '50–100 MG/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=800&auto=format&fit=crop',
    intPrice: 30,
    usaPrice: 55,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: true,
    description: 'Clomiphene Citrate (Clomid) stimulates natural testosterone production following an anabolic steroid cycle to prevent low-testosterone symptoms.',
  },
  {
    id: 7002,
    slug: 'nolvadex-7002',
    name: 'NOLVADEX 20',
    category: 'Post-Cycle Therapy (PCT)',
    categorySlug: 'post-cycle-therapy-3855',
    brand: 'Axiolabs',
    brandSlug: 'axiolabs-2078',
    substance: 'Tamoxifen Citrate',
    classification: 'SERM (ESTROGEN RECEPTOR ANTAGONIST)',
    form: '50 PILLS x 20 MG',
    halfLife: '5–7 DAYS',
    dosage: '20–40 MG/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop',
    intPrice: 28,
    usaPrice: 50,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: false,
    bestSeller: true,
    description: 'Tamoxifen Citrate (Nolvadex) is a selective estrogen receptor modulator used in PCT to block estrogen receptors and restart natural testosterone production.',
  },
  {
    id: 8001,
    slug: 'omega3-8001',
    name: 'OMEGA-3 FISH OIL',
    category: 'Supplements',
    categorySlug: 'supplements-3050',
    brand: 'Stealth Labs USA',
    brandSlug: 'stealth-labs-usa-3071',
    substance: 'Eicosapentaenoic / Docosahexaenoic Acid',
    classification: 'ESSENTIAL FATTY ACIDS',
    form: '120 SOFTGELS x 1000 MG',
    halfLife: 'N/A',
    dosage: '1–3 SOFTGELS/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO (LOWERS PRESSURE)',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1611926653458-09294b3142bf?q=80&w=800&auto=format&fit=crop',
    intPrice: 15,
    usaPrice: 25,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: false,
    description: 'High-potency Omega-3 Fish Oil to support cardiovascular health, joint lubrication, and optimal cholesterol profiles during cycles.',
  },
  {
    id: 8002,
    slug: 'multivitamin-8002',
    name: 'SPORTS MULTIVITAMIN',
    category: 'Supplements',
    categorySlug: 'supplements-3050',
    brand: 'Stealth Labs USA',
    brandSlug: 'stealth-labs-usa-3071',
    substance: 'Multivitamins & Minerals',
    classification: 'MICRONUTRIENTS',
    form: '90 TABLETS',
    halfLife: 'N/A',
    dosage: '1 TABLET/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=800&auto=format&fit=crop',
    intPrice: 18,
    usaPrice: 28,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: false,
    description: 'Premium sports multivitamin supplying all key micronutrients for metabolic support, muscle repair, and immune system strength.',
  },
  {
    id: 9001,
    slug: 'beginner-bulk-9001',
    name: 'BEGINNER BULKING CYCLE',
    category: 'Steroid Cycles',
    categorySlug: 'cycles-1933',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Test Cypionate / Dianabol / Arimidex / Nolvadex',
    classification: 'COMPLETE BULKING STACK',
    form: '12-WEEK CYCLE KIT',
    halfLife: 'MULTIPLE',
    dosage: 'FOLLOW INCLUDED GUIDE',
    acne: 'YES (POSSIBLE)',
    waterRetention: 'MODERATE',
    hbp: 'YES (MONITOR BP)',
    hepatotoxicity: 'YES (ORAL DIANABOL)',
    aromatization: 'YES (CONTROLLED)',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=800&auto=format&fit=crop',
    intPrice: 180,
    usaPrice: 290,
    intOriginalPrice: 360,
    usaOriginalPrice: 580,
    discounts: ['You will save $180.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-50% OFF', 'Best Value'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: true,
    description: 'The ultimate 12-week starter cycle designed to pack on massive size. Includes Testosterone Cypionate, Dianabol, aromatase inhibitors, and PCT recovery medication.',
  },
  {
    id: 9002,
    slug: 'advanced-cut-9002',
    name: 'ADVANCED CUTTING CYCLE',
    category: 'Steroid Cycles',
    categorySlug: 'cycles-1933',
    brand: 'Dragon Pharma',
    brandSlug: 'buy-2194',
    substance: 'Test Propionate / Tren Acetate / Winstrol / Clenbuterol',
    classification: 'COMPLETE CUTTING STACK',
    form: '10-WEEK CYCLE KIT',
    halfLife: 'MULTIPLE',
    dosage: 'FOLLOW INCLUDED GUIDE',
    acne: 'YES',
    waterRetention: 'NO',
    hbp: 'YES',
    hepatotoxicity: 'YES',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?q=80&w=800&auto=format&fit=crop',
    intPrice: 240,
    usaPrice: 390,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International', 'Highly Potent'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: false,
    bestSeller: true,
    description: 'A professional 10-week cutting protocol engineered to shred body fat while maintaining dry muscle mass. Includes Testosterone, Trenbolone, Stanozolol, and Clenbuterol.',
  },

  // ─── Peptide Hubs ──────────────────────────────────────────────────────────
  {
    id: 10001,
    slug: 'semaglutide-10001',
    name: 'SEMAGLUTIDE 5 MG',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Peptide Hubs',
    brandSlug: 'peptide-hubs-3750',
    substance: 'Semaglutide',
    classification: 'GLP-1 RECEPTOR AGONIST',
    form: '1 VIAL x 5 MG (LYOPHILIZED POWDER)',
    halfLife: '7 DAYS',
    dosage: '0.25–2.4 MG/WEEK',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO (HELPFUL)',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop',
    intPrice: 45,
    usaPrice: 80,
    intOriginalPrice: 75,
    usaOriginalPrice: 130,
    discounts: ['You will save $30.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-40% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: true,
    description: 'Semaglutide is a premium GLP-1 receptor agonist designed to reduce appetite, support weight loss, and optimize glycemic control.',
  },
  {
    id: 10002,
    slug: 'tb500-10002',
    name: 'TB-500 5 MG',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Peptide Hubs',
    brandSlug: 'peptide-hubs-3750',
    substance: 'Thymosin Beta-4',
    classification: 'TISSUE REPAIR PEPTIDE',
    form: '1 VIAL x 5 MG',
    halfLife: '7–10 DAYS',
    dosage: '2–5 MG/WEEK',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=800&auto=format&fit=crop',
    intPrice: 28,
    usaPrice: 50,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: false,
    bestSeller: false,
    description: 'TB-500 (Thymosin Beta-4) is a synthetic version of a naturally occurring healing peptide that accelerates tissue repair, muscle recovery, and joint healing.',
  },
  {
    id: 10003,
    slug: 'igf1-lr3-10003',
    name: 'IGF-1 LR3 1 MG',
    category: 'Peptides',
    categorySlug: 'peptides-414',
    brand: 'Peptide Hubs',
    brandSlug: 'peptide-hubs-3750',
    substance: 'Insulin-like Growth Factor-1 Long R3',
    classification: 'GROWTH FACTOR PEPTIDE',
    form: '1 VIAL x 1 MG (LYOPHILIZED POWDER)',
    halfLife: '20–30 HOURS',
    dosage: '20–120 MCG/DAY',
    acne: 'NO',
    waterRetention: 'LOW',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1611926653458-09294b3142bf?q=80&w=800&auto=format&fit=crop',
    intPrice: 38,
    usaPrice: 65,
    intOriginalPrice: 63,
    usaOriginalPrice: 108,
    discounts: ['You will save $25.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-40% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: false,
    bestSeller: true,
    description: 'IGF-1 LR3 is a potent growth factor peptide that promotes muscle hypertrophy, fat burning, and cellular growth by stimulating receptor sites more effectively than natural IGF-1.',
  },

  // ─── British Dragon Pharma ─────────────────────────────────────────────────
  {
    id: 11001,
    slug: 'halotestin-11001',
    name: 'HALOTESTIN 10',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'British Dragon Pharma',
    brandSlug: 'british-dragon-2079',
    substance: 'Fluoxymesterone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 10 MG',
    halfLife: '9.2 HOURS',
    dosage: 'MEN 10–40 MG/DAY',
    acne: 'YES (HIGH)',
    waterRetention: 'NO',
    hbp: 'YES',
    hepatotoxicity: 'YES (HIGH)',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/dianabol-20-2807--s512.webp',
    intPrice: 95,
    usaPrice: 160,
    intOriginalPrice: 190,
    usaOriginalPrice: 320,
    discounts: ['You will save $95.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-50% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: false,
    description: 'Halotestin (Fluoxymesterone) is an extremely powerful oral androgenic steroid utilized by powerlifters and bodybuilders for extreme strength and aggression gains without water weight.',
  },
  {
    id: 11002,
    slug: 'decabol-11002',
    name: 'DECA-BOL 250',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'British Dragon Pharma',
    brandSlug: 'british-dragon-2079',
    substance: 'Nandrolone Decanoate',
    classification: 'ANDROGEN; ANABOLIC STEROID; PROGESTOGEN',
    form: '10 ML VIAL x 250 MG',
    halfLife: '15 DAYS',
    dosage: 'MEN 200–600 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'LOW',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/cypionat-2917--s512.webp',
    intPrice: 42,
    usaPrice: 80,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: true,
    description: 'Deca-Bol (Nandrolone Decanoate) is an exceptionally popular injectable steroid for bulking cycles, providing significant joint relief, nitrogen retention, and raw mass growth.',
  },
  {
    id: 11003,
    slug: 'oxanabol-11003',
    name: 'OXANABOL 10',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'British Dragon Pharma',
    brandSlug: 'british-dragon-2079',
    substance: 'Oxandrolone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 10 MG',
    halfLife: '9 HOURS',
    dosage: 'MEN 20–80 MG/DAY',
    acne: 'RARELY',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/anavar-10-2838--s512.webp',
    intPrice: 110,
    usaPrice: 185,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: false,
    bestSeller: true,
    description: 'Oxanabol 10 (Oxandrolone) by British Dragon is a mild yet effective cutting oral steroid for lean muscle retention, strength, and definition.',
  },

  // ─── Kalpa Pharmaceuticals ─────────────────────────────────────────────────
  {
    id: 12001,
    slug: 'trenaplex-12001',
    name: 'TRENAPLEX A 100',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Kalpa Pharmaceuticals',
    brandSlug: 'kalpa-1715',
    substance: 'Trenbolone Acetate',
    classification: 'ANDROGEN ESTER; ANABOLIC STEROID; PROGESTOGEN',
    form: '10 ML VIAL x 100 MG',
    halfLife: '1–1.5 DAYS',
    dosage: 'MEN 150–350 MG/WEEK',
    acne: 'YES',
    waterRetention: 'NO',
    hbp: 'YES',
    hepatotoxicity: 'YES',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/trenbolone-200-2924--s512.webp',
    intPrice: 65,
    usaPrice: 115,
    intOriginalPrice: 130,
    usaOriginalPrice: 230,
    discounts: ['You will save $65.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-50% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: true,
    description: 'Trenaplex A 100 (Trenbolone Acetate) is a highly anabolic, fast-acting injectable compound that promotes dramatic gains in muscle definition, hardness, and raw strength.',
  },
  {
    id: 12002,
    slug: 'proximed-12002',
    name: 'PROXIMED 25',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'Kalpa Pharmaceuticals',
    brandSlug: 'kalpa-1715',
    substance: 'Mesterolone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '50 PILLS x 25 MG',
    halfLife: '12 HOURS',
    dosage: 'MEN 25–50 MG/DAY',
    acne: 'YES',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/winstrol-50-2822--s512.webp',
    intPrice: 35,
    usaPrice: 60,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: false,
    description: 'Proximed 25 (Proviron) binds strongly to SHBG to increase circulating free testosterone, improving muscle hardness, libido, and reducing estrogenic side effects.',
  },
  {
    id: 12003,
    slug: 'testoxyl-12003',
    name: 'TESTOXYL CYPIONATE 250',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Kalpa Pharmaceuticals',
    brandSlug: 'kalpa-1715',
    substance: 'Testosterone Cypionate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 250 MG',
    halfLife: '15–16 DAYS',
    dosage: 'MEN 250–750 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'YES',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/cypionat-2917--s512.webp',
    intPrice: 32,
    usaPrice: 60,
    discounts: [],
    suggestions: [],
    ribbons: ['Lab Tested', 'Domestic & International'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: false,
    bestSeller: true,
    description: 'Testoxyl Cypionate 250 is Kalpa Pharmaceuticals\' flagship testosterone ester for sustained anabolic activity, bulk gains, and full hormonal support.',
  },

  // ─── Gen-Shi Laboratories ──────────────────────────────────────────────────
  {
    id: 13001,
    slug: 'testoenant-13001',
    name: 'TESTOSTERONE E 250',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Gen-Shi Laboratories',
    brandSlug: 'gen-shi-1736',
    substance: 'Testosterone Enanthate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 250 MG',
    halfLife: '10–14 DAYS',
    dosage: 'MEN 250–750 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'YES',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/enantat-250-2913--s512.webp',
    intPrice: 38,
    usaPrice: 70,
    intOriginalPrice: 76,
    usaOriginalPrice: 140,
    discounts: ['You will save $38.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-50% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: true,
    bestSeller: true,
    description: 'Gen-Shi Test E 250 is a pure Testosterone Enanthate ester designed for sustained release to support building raw size, strength, and endurance.',
  },
  {
    id: 13002,
    slug: 'turinabol-13002',
    name: 'TURINABOL 10',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'Gen-Shi Laboratories',
    brandSlug: 'gen-shi-1736',
    substance: '4-Chlorodehydromethyltestosterone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 10 MG',
    halfLife: '16 HOURS',
    dosage: 'MEN 20–50 MG/DAY',
    acne: 'YES',
    waterRetention: 'NO',
    hbp: 'PERHAPS',
    hepatotoxicity: 'YES',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/anavar-10-2838--s512.webp',
    intPrice: 45,
    usaPrice: 85,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: false,
    description: 'Turinabol 10 is an oral anabolic steroid known for clean, quality dry muscle gains with zero water retention and low androgenic side effects.',
  },
  {
    id: 13003,
    slug: 'primoxyl-13003',
    name: 'PRIMOXYL 100',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Gen-Shi Laboratories',
    brandSlug: 'gen-shi-1736',
    substance: 'Methenolone Enanthate',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER',
    form: '10 ML VIAL x 100 MG',
    halfLife: '10.5 DAYS',
    dosage: 'MEN 300–600 MG/WEEK',
    acne: 'RARELY',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/masteron-100-2918--s512.webp',
    intPrice: 85,
    usaPrice: 145,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: false,
    description: 'Primoxyl 100 (Primobolan Depot) is a mild injectable anabolic for lean muscle preservation during cutting cycles, with minimal side effects and no aromatization.',
  },

  // ─── Axiolabs (additional products) ────────────────────────────────────────
  {
    id: 14001,
    slug: 'axio-sustanon-14001',
    name: 'SUSTAXYL 350',
    category: 'Injectable Anabolic Steroids',
    categorySlug: 'injectables-391',
    brand: 'Axiolabs',
    brandSlug: 'axiolabs-2078',
    substance: 'Testosterone Mix',
    classification: 'ANDROGEN; ANABOLIC STEROID; ANDROGEN ESTER MIX',
    form: '10 ML VIAL x 350 MG',
    halfLife: '7–8 DAYS',
    dosage: 'MEN 350–700 MG/WEEK',
    acne: 'YES',
    waterRetention: 'YES',
    hbp: 'PERHAPS',
    hepatotoxicity: 'NO',
    aromatization: 'YES',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/sustanon-2912--s512.webp',
    intPrice: 58,
    usaPrice: 100,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: true,
    description: 'Sustaxyl 350 is Axiolabs\' high-concentration testosterone blend providing synergistic anabolic effects from four esterified testosterones for exceptional size and strength.',
  },
  {
    id: 14002,
    slug: 'axio-anavar-14002',
    name: 'OXANDROPLEX 10',
    category: 'Oral Anabolic Steroids',
    categorySlug: 'orals-380',
    brand: 'Axiolabs',
    brandSlug: 'axiolabs-2078',
    substance: 'Oxandrolone',
    classification: 'ANDROGEN; ANABOLIC STEROID',
    form: '100 PILLS x 10 MG',
    halfLife: '9 HOURS',
    dosage: 'MEN 20–80 MG/DAY',
    acne: 'RARELY',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/products/anavar-50-2866--s512.webp',
    intPrice: 105,
    usaPrice: 165,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: true,
    bestSeller: true,
    description: 'Oxandroplex 10 (Oxandrolone) by Axiolabs is the go-to oral cutting steroid for lean mass preservation, strength boosts, and a tight, hard physique.',
  },

  // ─── Stealth Labs USA (additional products) ────────────────────────────────
  {
    id: 15001,
    slug: 'stealth-lgd4033-15001',
    name: 'LGD 4033 (LIGANDROL)',
    category: 'SARMs',
    categorySlug: 'sarms-2034',
    brand: 'Stealth Labs USA',
    brandSlug: 'stealth-labs-usa-3071',
    substance: 'Ligandrol (LGD-4033)',
    classification: 'SELECTIVE ANDROGEN RECEPTOR MODULATOR',
    form: '50 TABS x 5 MG',
    halfLife: '24–36 HOURS',
    dosage: 'MEN 5–10 MG/DAY',
    acne: 'NO',
    waterRetention: 'LOW',
    hbp: 'NO',
    hepatotoxicity: 'LOW',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=800&auto=format&fit=crop',
    intPrice: 42,
    usaPrice: 75,
    intOriginalPrice: 70,
    usaOriginalPrice: 125,
    discounts: ['You will save $28.00'],
    suggestions: [],
    ribbons: ['Domestic & International', '-40% OFF'],
    labTested: true,
    labTestImage: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp',
    featured: false,
    bestSeller: true,
    description: 'LGD-4033 (Ligandrol) is one of the most anabolic SARMs available, producing significant lean muscle gains and strength improvements without the harsh androgenic side effects of traditional steroids.',
  },
  {
    id: 15002,
    slug: 'stealth-osta-15002',
    name: 'OSTARINE (MK-2866)',
    category: 'SARMs',
    categorySlug: 'sarms-2034',
    brand: 'Stealth Labs USA',
    brandSlug: 'stealth-labs-usa-3071',
    substance: 'Ostarine (MK-2866)',
    classification: 'SELECTIVE ANDROGEN RECEPTOR MODULATOR',
    form: '50 TABS x 25 MG',
    halfLife: '23.8 HOURS',
    dosage: 'MEN 10–30 MG/DAY',
    acne: 'NO',
    waterRetention: 'NO',
    hbp: 'NO',
    hepatotoxicity: 'NO',
    aromatization: 'NO',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=800&auto=format&fit=crop',
    intPrice: 35,
    usaPrice: 60,
    discounts: [],
    suggestions: [],
    ribbons: ['Domestic & International'],
    labTested: false,
    featured: false,
    bestSeller: false,
    description: 'Ostarine (MK-2866) is the most studied SARM on the market, widely used for body recomposition, lean muscle preservation, joint repair, and beginner SARM cycles.',
  },
];

export const categories = [
  { name: 'Oral Anabolic Steroids', slug: 'orals-380' },
  { name: 'Injectable Anabolic Steroids', slug: 'injectables-391' },
  { name: 'SARMs', slug: 'sarms-2034' },
  { name: 'Post-Cycle Therapy (PCT)', slug: 'post-cycle-therapy-3855' },
  { name: 'Fat Loss', slug: 'fat-loss-397' },
  { name: 'Sexual Health', slug: 'sexual-health-415' },
  { name: 'Peptides', slug: 'peptides-414' },
  { name: 'Supplements', slug: 'supplements-3050' },
  { name: 'Steroid Cycles', slug: 'cycles-1933' },
];

export const brands = [
  { name: 'Dragon Pharma', slug: 'buy-2194' },
  { name: 'Axiolabs', slug: 'axiolabs-2078' },
  { name: 'British Dragon Pharma', slug: 'british-dragon-2079' },
  { name: 'Kalpa Pharmaceuticals', slug: 'kalpa-1715' },
  { name: 'Generic Asia', slug: 'generic-asia-3391' },
  { name: 'Gen-Shi Laboratories', slug: 'gen-shi-1736' },
  { name: 'Peptide Hubs', slug: 'peptide-hubs-3750' },
  { name: 'Stealth Labs USA', slug: 'stealth-labs-usa-3071' },
];

export const sales = [
  { name: 'Weekly Deals', suffix: '-50% OFF', slug: 'weekly-deals-4304' },
  { name: 'Special Sale', suffix: '-40% OFF', slug: 'exclusive-deals-3047' },
  { name: 'Clearance', suffix: '-30% OFF', slug: 'clearance-4305' },
  { name: 'Buy 3 Get 1 FREE', suffix: 'PROMO', slug: 'promo-4068' },
];

export const warehouses = [
  { name: 'US Domestic Warehouse 🇺🇸', slug: 'us-domestic-warehouse-3401' },
  { name: 'International Warehouse 🌏', slug: 'international-warehouse-3421' },
];

export const labReports = [
  { product: 'Anavar 10', date: '2026-03-26', verified: '9.08 mg', productSlug: 'orals-380/anavar-2838', image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/anavar-10-lab-test-2026-03-26.webp' },
  { product: 'Testo Blend 350', date: '2026-03-25', verified: '346.63 mg', productSlug: 'injectables-391/testo-blend-36988', image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/testo-blend-lab-test-2026-03-25.webp' },
  { product: 'Sustanon 270', date: '2026-03-25', verified: '271.26 mg', productSlug: 'injectables-391/sustanon-2912', image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/sustanon-270-lab-test-2026-03-25.webp' },
  { product: 'Enantat 250', date: '2026-03-25', verified: '264.62 mg', productSlug: 'injectables-391/enantat-2913', image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/enantat-250-lab-test-2026-03-25.webp' },
  { product: 'Cut Mix 150', date: '2026-03-25', verified: '158.41 mg', productSlug: 'injectables-391/cut-mix-2930', image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/cut-mix-lab-test-2026-03-25.webp' },
  { product: 'Masteron 200', date: '2026-03-25', verified: '198.4 mg', productSlug: 'injectables-391/masteron-2919', image: 'https://www.dragonpharma.net/uploads/dragonpharmanet/masteron-200-lab-test-2026-03-25.webp' },
];

// ─── Column Mapping Helpers ──────────────────────────────────────────────────
// PostgreSQL lowercases all unquoted column names. Our DB columns are all
// lowercase (categoryslug, brandslug, intprice, usaprice, halflife, etc.)
// but our TypeScript interface uses camelCase. These helpers convert between them.

const PRODUCT_CAMEL_TO_DB: Record<string, string> = {
  categorySlug: 'categoryslug',
  brandSlug: 'brandslug',
  halfLife: 'halflife',
  waterRetention: 'waterretention',
  intPrice: 'intprice',
  usaPrice: 'usaprice',
  intOriginalPrice: 'intoriginalprice',
  usaOriginalPrice: 'usaoriginalprice',
  labTested: 'labtested',
  labTestImage: 'labtestimage',
  bestSeller: 'bestseller',
};

const PRODUCT_DB_TO_CAMEL: Record<string, string> = {};
for (const [camel, db] of Object.entries(PRODUCT_CAMEL_TO_DB)) {
  PRODUCT_DB_TO_CAMEL[db] = camel;
}

function dbRowToProduct(row: Record<string, unknown>): Product {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(row)) {
    if (key === 'created_at') continue; // skip DB-only column
    const camelKey = PRODUCT_DB_TO_CAMEL[key] || key;
    result[camelKey] = value;
  }
  return result as unknown as Product;
}

function productToDbRow(prod: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(prod)) {
    const dbKey = PRODUCT_CAMEL_TO_DB[key] || key;
    result[dbKey] = value;
  }
  return result;
}

let lastFetchTime = 0;
const FETCH_COOLDOWN = 10000; // 10 seconds cooldown between background refreshes

export function fetchProductsFromSupabase() {
  if (typeof window === 'undefined') return;
  const now = Date.now();
  if (now - lastFetchTime < FETCH_COOLDOWN) return;
  lastFetchTime = now;

  supabase
    .from('products')
    .select('*')
    .order('id', { ascending: true })
    .then(({ data, error }) => {
      if (error) {
        console.error('Failed to sync products from Supabase:', error.message);
        return;
      }
      if (data && data.length > 0) {
        // Map DB lowercase columns to camelCase interface
        const mapped = data.map(row => dbRowToProduct(row as Record<string, unknown>));
        localStorage.setItem('dp_products', JSON.stringify(mapped));
        window.dispatchEvent(new Event('dp_products_updated'));
      }
    });
}

export function getStoredProducts(): Product[] {
  if (typeof window === 'undefined') return products;
  const stored = localStorage.getItem('dp_products');
  
  // Trigger background revalidation fetch
  fetchProductsFromSupabase();

  if (!stored) {
    localStorage.setItem('dp_products', JSON.stringify(products));
    return products;
  }
  try {
    return JSON.parse(stored);
  } catch (e) {
    return products;
  }
}

export function saveStoredProducts(list: Product[]) {
  if (typeof window !== 'undefined') {
    localStorage.setItem('dp_products', JSON.stringify(list));
    window.dispatchEvent(new Event('dp_products_updated'));
  }
}

export async function addProduct(prod: Omit<Product, 'id' | 'slug'>): Promise<Product> {
  const list = getStoredProducts();
  const nextId = list.length > 0 ? Math.max(...list.map(p => p.id)) + 1 : 1000;
  const slug = `${prod.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${nextId}`;
  const newProduct: Product = {
    ...prod,
    id: nextId,
    slug
  };

  // Convert camelCase to lowercase for DB
  const dbRow = productToDbRow(newProduct as unknown as Record<string, unknown>);
  const { error } = await supabase.from('products').insert([dbRow]);
  if (error) {
    console.error('Supabase add product error:', error.message);
    throw error;
  }

  list.push(newProduct);
  saveStoredProducts(list);
  return newProduct;
}

export async function updateProduct(id: number, updated: Partial<Product>): Promise<boolean> {
  const list = getStoredProducts();
  const idx = list.findIndex(p => p.id === id);
  if (idx === -1) return false;

  const mergedProduct = { ...list[idx], ...updated };

  // Convert camelCase to lowercase for DB
  const dbUpdated = productToDbRow(updated as Record<string, unknown>);
  const { error } = await supabase
    .from('products')
    .update(dbUpdated)
    .eq('id', id);

  if (error) {
    console.error('Supabase update product error:', error.message);
    throw error;
  }

  list[idx] = mergedProduct;
  saveStoredProducts(list);
  return true;
}

export async function deleteProduct(id: number): Promise<boolean> {
  const list = getStoredProducts();
  const filtered = list.filter(p => p.id !== id);
  if (filtered.length === list.length) return false;

  const { error } = await supabase
    .from('products')
    .delete()
    .eq('id', id);

  if (error) {
    console.error('Supabase delete product error:', error.message);
    throw error;
  }

  saveStoredProducts(filtered);
  return true;
}

export function getProductsByCategory(slug: string): Product[] {
  return getStoredProducts().filter(p => p.categorySlug === slug);
}

export function getProductsByBrand(slug: string): Product[] {
  return getStoredProducts().filter(p => p.brandSlug === slug);
}

export function getFeaturedProducts(): Product[] {
  return getStoredProducts().filter(p => p.featured);
}

export function getBestSellers(): Product[] {
  return getStoredProducts().filter(p => p.bestSeller);
}

export function getProductBySlug(slug: string): Product | undefined {
  return getStoredProducts().find(p => p.slug === slug);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return getStoredProducts().filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.substance.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q)
  );
}
